<?php
global $cfg_Cs;
$cfg_Cs=array();
$cfg_Cs[2]=array(0,1,1,'55S15b2x');
$cfg_Cs[3]=array(0,1,1,'5Zu95Lqn5Ymn');
$cfg_Cs[4]=array(0,1,1,'5rGC54mH5Yy6');
$cfg_Cs[5]=array(0,17,1,'5bm754Gv54mH');
$cfg_Cs[6]=array(0,1,1,'576O5Ymn');
$cfg_Cs[7]=array(0,1,1,'6Z+p5Ymn');
$cfg_Cs[8]=array(0,1,1,'5YW25LuW5Ymn');
$cfg_Cs[9]=array(0,1,1,'5aW95Z+65Y+L');
$cfg_Cs[11]=array(2,2,1,'5Zu95Lqn55S15b2x');
$cfg_Cs[13]=array(3,2,1,'54ix5oOF');
?>