<?php
$z[0]=Array("field","北京物业管理资质新办资",0,74);
$z[0][4]['name']="keywords";
$z[1]=Array("field","北京物业管理资质新办资料清单 北京物业管理资质新办资料清单。想在北京成立一家物管管理公司，申请物业资质是必须的，那么，首次申请物业管理资质需要准备些什么资料呢?下面",76,362);
$z[1][4]['name']="description";
$z[2]=Array("field","北京物业管理资质新办资料清单-资质管家",364,457);
$z[2][4]['name']="title";
$z[3]=Array("field","",459,498);
$z[3][4]['name']="writer";
$z[4]=Array("field","",500,539);
$z[4][4]['name']="source";
$z[5]=Array("field","",541,581);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",583,620);
$z[6][4]['name']="body";
$z[7]=Array("field","",622,661);
$z[7][4]['name']="litpic";

?>