{dede:field name='keywords'}北京物业管理资质新办资{/dede:field}
{dede:field name='description'}北京物业管理资质新办资料清单 北京物业管理资质新办资料清单。想在北京成立一家物管管理公司，申请物业资质是必须的，那么，首次申请物业管理资质需要准备些什么资料呢?下面{/dede:field}
{dede:field name='title'}北京物业管理资质新办资料清单-资质管家{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='litpic'}{/dede:field}
