{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}原标题：评论| 中国高铁岂容硕鼠作祟？近日，中国铁路总公司内部人士证实了网友日前发布的一份通报。该《中国铁路总公司关于沪昆高铁贵州段质量问题处理情况的通报（铁总建设函{/dede:field}
{dede:field name='title'}央视：中国高铁岂容硕鼠作祟？_凤凰资讯{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='litpic'}{/dede:field}
