<?php
$z[0]=Array("field","",0,41);
$z[0][4]['name']="keywords";
$z[1]=Array("field","原标题：评论| 中国高铁岂容硕鼠作祟？近日，中国铁路总公司内部人士证实了网友日前发布的一份通报。该《中国铁路总公司关于沪昆高铁贵州段质量问题处理情况的通报（铁总建设函",43,332);
$z[1][4]['name']="description";
$z[2]=Array("field","央视：中国高铁岂容硕鼠作祟？_凤凰资讯",334,427);
$z[2][4]['name']="title";
$z[3]=Array("field","",429,468);
$z[3][4]['name']="writer";
$z[4]=Array("field","",470,509);
$z[4][4]['name']="source";
$z[5]=Array("field","",511,551);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",553,590);
$z[6][4]['name']="body";
$z[7]=Array("field","",592,631);
$z[7][4]['name']="litpic";

?>