{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}原标题：天价手机靓号重出江湖 杜绝灰色交易考验监管动辄几万甚至几百万的手机靓号近日成舆论焦点，有声音称是运营商变相收费，可运营商真是“哑巴吃黄连”，据悉，天价靓号背{/dede:field}
{dede:field name='title'}天价手机靓号重出江湖 杜绝灰色交易考验监管{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='litpic'}{/dede:field}
