<?php
$z[0]=Array("field","",0,41);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",43,87);
$z[1][4]['name']="description";
$z[2]=Array("field","第4季中国好演员启动仪式 陈好久违亮相气质依旧_娱乐频道_凤凰网",89,215);
$z[2][4]['name']="title";
$z[3]=Array("field","",217,256);
$z[3][4]['name']="writer";
$z[4]=Array("field","",258,297);
$z[4][4]['name']="source";
$z[5]=Array("field","",299,339);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",341,378);
$z[6][4]['name']="body";
$z[7]=Array("field","",380,419);
$z[7][4]['name']="litpic";

?>