<li class="dropdown margin-left-30"> <a ahef"{dede:field name='typeurl'/}"= class="dropdown-toggle animation-zoomIn link "   data-toggle="dropdown" data-hover="dropdown"aria-expanded="false" role="button" href="{dede:field name='typeurl'/}" >{dede:field name='typename'/} <i class="fa fa-angle-down"></i></a>
         <!-- <ul class="dropdown-menu dropdown-menu-right bullet " role="menu" >
              {dede:channel type='son' noself='yes'} 
              <li class="animation-fade animation-delay-"><a href="[field:typelink/]" class=" animation-fade "  title="[field:typename/] ">[field:typename/] </a></li>
              {/dede:channel} 
            </ul>-->
          </li>