<?php
$z[0]=Array("field","",45,73);
$z[0][4]['name']="typeurl";
$z[1]=Array("field","",211,239);
$z[1][4]['name']="typeurl";
$z[2]=Array("field","",242,271);
$z[2][4]['name']="typename";
$z[3]=Array("channel"," \r\n              <li class=\"animation-fade animation-delay-\"><a href=\"[field:typelink/]\" class=\" animation-fade \"  title=\"[field:typename/] \">[field:typename/] </a></li>\r\n              ",407,645);
$z[3][4]['type']="son";
$z[3][4]['noself']="yes";

?>