<?php
$z[0]=Array("field","",0,41);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",43,87);
$z[1][4]['name']="description";
$z[2]=Array("field","许晴前男友刘波在日本去世 生前旧照回顾_娱乐频道_凤凰网",89,205);
$z[2][4]['name']="title";
$z[3]=Array("field","",207,246);
$z[3][4]['name']="writer";
$z[4]=Array("field","",248,287);
$z[4][4]['name']="source";
$z[5]=Array("field","",289,329);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",331,368);
$z[6][4]['name']="body";
$z[7]=Array("field","",370,409);
$z[7][4]['name']="litpic";

?>