<?php
$z[0]=Array("field","工程招标代理资质申请流",0,74);
$z[0][4]['name']="keywords";
$z[1]=Array("field","工程招标代理资质对于很多建筑企业老板来说都不陌生，资质管家也总接到很多电话咨询招标代理资质办理相关事宜，今天小编就来和大家讲讲工程招标代理资质申请流程是什么！ 一、",76,364);
$z[1][4]['name']="description";
$z[2]=Array("field","工程招标代理资质申请流程是什么-资质管家",366,462);
$z[2][4]['name']="title";
$z[3]=Array("field","",464,503);
$z[3][4]['name']="writer";
$z[4]=Array("field","",505,544);
$z[4][4]['name']="source";
$z[5]=Array("field","",546,586);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",588,625);
$z[6][4]['name']="body";
$z[7]=Array("field","",627,666);
$z[7][4]['name']="litpic";

?>