{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}原标题：高铁之后，中国的下一张名片可能是它作为中国拥有自主知识产权的商用干线飞机，C919的每一次动态都引起国人的关注。当前，C919已经从上海转场至西安阎良试飞院，成功完成{/dede:field}
{dede:field name='title'}高铁之后，中国的下一张名片可能是它_凤凰资讯{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='litpic'}{/dede:field}
