<?php
$z[0]=Array("field","企业资质证书",0,59);
$z[0][4]['name']="keywords";
$z[1]=Array("field","企业资质证书经济性质变更了应该怎么办?原来的资质是否还能在用?这些都是企业比较关心的问题，那么企业资质证书经济性质变更了该怎么办呢?资质管家与您作如下分享： 企业资质证",61,349);
$z[1][4]['name']="description";
$z[2]=Array("field","企业资质证书经济性质变更了应该怎么办？-资质管家",351,459);
$z[2][4]['name']="title";
$z[3]=Array("field","",461,500);
$z[3][4]['name']="writer";
$z[4]=Array("field","",502,541);
$z[4][4]['name']="source";
$z[5]=Array("field","",543,583);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",585,622);
$z[6][4]['name']="body";
$z[7]=Array("field","",624,663);
$z[7][4]['name']="litpic";

?>