<?php
$z[0]=Array("field","",0,41);
$z[0][4]['name']="keywords";
$z[1]=Array("field","快递中受损的燕窝 受访者供图今年4月12日，自贡市民杨女士通过四川顺丰速运有限公司自贡分公司（以下简称“顺丰速运”）向北京邮寄10斤燕窝，并支付了391元快递费，另付1000元保价",43,331);
$z[1][4]['name']="description";
$z[2]=Array("field","四川女子保价20万的燕窝寄碎了！被判全额赔偿后顺丰不干了",333,451);
$z[2][4]['name']="title";
$z[3]=Array("field","",453,492);
$z[3][4]['name']="writer";
$z[4]=Array("field","",494,533);
$z[4][4]['name']="source";
$z[5]=Array("field","",535,575);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",577,614);
$z[6][4]['name']="body";
$z[7]=Array("field","",616,655);
$z[7][4]['name']="litpic";

?>