{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}快递中受损的燕窝 受访者供图今年4月12日，自贡市民杨女士通过四川顺丰速运有限公司自贡分公司（以下简称“顺丰速运”）向北京邮寄10斤燕窝，并支付了391元快递费，另付1000元保价{/dede:field}
{dede:field name='title'}四川女子保价20万的燕窝寄碎了！被判全额赔偿后顺丰不干了{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='litpic'}{/dede:field}
