<?php
$z[0]=Array("field","注册资本",0,53);
$z[0][4]['name']="keywords";
$z[1]=Array("field","谈到公司注册的注册资金，就有了实缴制和认缴制的说法，那什么是实缴制，什么是认缴制呢，注册资本是不是越大越好?下面资质管家小编为大家详细解析。 一、关于认缴制、实缴制",55,341);
$z[1][4]['name']="description";
$z[2]=Array("field","注册公司，“认缴”与“实缴”究竟哪个更好？-资质管家",343,457);
$z[2][4]['name']="title";
$z[3]=Array("field","",459,498);
$z[3][4]['name']="writer";
$z[4]=Array("field","",500,539);
$z[4][4]['name']="source";
$z[5]=Array("field","",541,581);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",583,620);
$z[6][4]['name']="body";
$z[7]=Array("field","",622,661);
$z[7][4]['name']="litpic";

?>