{dede:field name='keywords'}建筑资质转让失败的原因{/dede:field}
{dede:field name='description'}大家都知道，建筑企业想招投标，就需要有施工资质，但是资质办理的过程通常比较漫长和复杂，很多觉得麻烦的建筑企业就选择购买一个资质。因为新办建筑资质耗费的时间很长而且{/dede:field}
{dede:field name='title'}建筑资质转让失败的原因-资质管家{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='litpic'}{/dede:field}
