<?php
$z[0]=Array("arcurl","",113,128);
$z[1]=Array("title","",137,151);
$z[2]=Array("picname","",200,216);
$z[3]=Array("title","",245,259);
$z[4]=Array("arcurl","",375,390);
$z[5]=Array("title","",399,413);
$z[6]=Array("title","",430,444);
$z[7]=Array("description","",491,541);
$z[7][4]['function']="cn_substr(@me,700)";
$z[8]=Array("pubdate","",593,640);
$z[8][4]['function']="GetDateTimeMK(@me)";
$z[9]=Array("typename","",654,671);
$z[10]=Array("click","",746,760);

?>