<li class=" shown">
          <div class="widget widget-shadow">
            <figure class="widget-header cover"> <a href="[field:arcurl/]" title="[field:shorttitle/]" target='_self'>
              <div class="mask"> </div>
              <img class="cover-image"  src="[field:picname/]" alt="[field:title/]"> </a> </figure>
            <h4 class="widget-title"> <a href="[field:arcurl/]"  title="[field:title/]" target='_self' style="height: 160px;">[field:title/]</a>
              <p>[field:description function="cn_substr(@me,30)"/]...</p>
            </h4>
          </div>
        </li>