<?php
$z[0]=Array("field","消防设施工程专业资质如",0,74);
$z[0][4]['name']="keywords";
$z[1]=Array("field","消防设施工程专业资质如何办理? 消防设施工程专业承资质划分为一级、二级、三级，资质等级的标准及承包工程范围按照建设部现行《建筑业企业资质等级标准》执行。申请消防设施",76,362);
$z[1][4]['name']="description";
$z[2]=Array("field","消防设施工程专业资质如何办理?-资质管家",364,458);
$z[2][4]['name']="title";
$z[3]=Array("field","",460,499);
$z[3][4]['name']="writer";
$z[4]=Array("field","",501,540);
$z[4][4]['name']="source";
$z[5]=Array("field","",542,582);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",584,621);
$z[6][4]['name']="body";
$z[7]=Array("field","",623,662);
$z[7][4]['name']="litpic";

?>