{dede:field name='keywords'}消防设施工程专业资质如{/dede:field}
{dede:field name='description'}消防设施工程专业资质如何办理? 消防设施工程专业承资质划分为一级、二级、三级，资质等级的标准及承包工程范围按照建设部现行《建筑业企业资质等级标准》执行。申请消防设施{/dede:field}
{dede:field name='title'}消防设施工程专业资质如何办理?-资质管家{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='litpic'}{/dede:field}
