<?php
$z[0]=Array("sppage","",0,73);
$z[0][4]['sptype']="full";
$z[0][4]['srul']="1";
$z[0][4]['erul']="5";
$z[1]=Array("previewurl","http://www.cnbeta.com/articles/tech/689799.htm",75,156);
$z[2]=Array("keywordtrim","",158,195);
$z[3]=Array("descriptiontrim","",197,242);
$z[4]=Array("item","\r\n   {dede:match}<h1>[内容]</h1>{/dede:match}\r\n   {dede:trim replace=''}<a([^>]*)>(.*)</a>{/dede:trim}\r\n   {dede:function}{/dede:function}\r\n",244,452);
$z[4][4]['field']="title";
$z[4][4]['value']="";
$z[4][4]['isunit']="";
$z[4][4]['isdown']="";
$z[5]=Array("item","\r\n   {dede:match}{/dede:match}\r\n   \r\n   {dede:function}{/dede:function}\r\n",454,594);
$z[5][4]['field']="writer";
$z[5][4]['value']="";
$z[5][4]['isunit']="";
$z[5][4]['isdown']="";
$z[6]=Array("item","\r\n   {dede:match}<div class=\"article-summary\">[内容]<div class=\"article-share-code\">{/dede:match}\r\n   {dede:trim replace=''}<img([^>]*)>{/dede:trim}\r\n   {dede:function}{/dede:function}\r\n",596,851);
$z[6][4]['field']="source";
$z[6][4]['value']="";
$z[6][4]['isunit']="";
$z[6][4]['isdown']="";
$z[7]=Array("item","\r\n   {dede:match}{/dede:match}\r\n   \r\n   {dede:function}@me=GetMkTime(@me);{/dede:function}\r\n",853,1013);
$z[7][4]['field']="pubdate";
$z[7][4]['value']="";
$z[7][4]['isunit']="";
$z[7][4]['isdown']="";
$z[8]=Array("item","\r\n   {dede:match}{/dede:match}\r\n   \r\n   {dede:function}{/dede:function}\r\n",1015,1155);
$z[8][4]['field']="body";
$z[8][4]['value']="";
$z[8][4]['isunit']="1";
$z[8][4]['isdown']="1";

?>