<?php
$z[0]=Array("field","装饰装修资质",0,59);
$z[0][4]['name']="keywords";
$z[1]=Array("field","近日，有粉丝给资质管家小编留言问：想要办理装饰装修资质，不知道明年政策会有什么变化吗? 目前为止，资质改革的形势是把不必要的资质认定和管理统统取消，必备的资质会继续",61,347);
$z[1][4]['name']="description";
$z[2]=Array("field","最新建筑装饰装修资质需要多少代办费?-资质管家",349,452);
$z[2][4]['name']="title";
$z[3]=Array("field","",454,493);
$z[3][4]['name']="writer";
$z[4]=Array("field","",495,534);
$z[4][4]['name']="source";
$z[5]=Array("field","",536,576);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",578,615);
$z[6][4]['name']="body";
$z[7]=Array("field","",617,656);
$z[7][4]['name']="litpic";

?>