<?php
$z[0]=Array("noteinfo","",0,188);
$z[0][4]['notename']="文章";
$z[0][4]['channelid']="1";
$z[0][4]['macthtype']="string";
$z[0][4]['refurl']="http://blog.sanjieke.cn/index.html";
$z[0][4]['sourcelang']="utf-8";
$z[0][4]['cosort']="asc";
$z[0][4]['isref']="no";
$z[0][4]['exptime']="10";
$z[0][4]['usemore']="0";
$z[1]=Array("listrule","\r\n    {dede:addurls}{/dede:addurls}\r\n    {dede:batchrule}{/dede:batchrule}\r\n    {dede:regxrule}{/dede:regxrule}\r\n    {dede:areastart}{/dede:areastart}\r\n    {dede:areaend}{/dede:areaend}\r\n",190,580);
$z[1][4]['sourcetype']="batch";
$z[1][4]['rssurl']="";
$z[1][4]['regxurl']="http://blog.sanjieke.cn/article/(*)";
$z[1][4]['startid']="1";
$z[1][4]['endid']="2521";
$z[1][4]['addv']="1";
$z[1][4]['urlrule']="area";
$z[1][4]['musthas']="";
$z[1][4]['nothas']="";
$z[1][4]['listpic']="1";
$z[1][4]['usemore']="0";

?>