{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}这是来自一位网友的自诉：我叫小圆，家里还有一个比我小三岁的弟弟，从小爸妈为生计就长年在外地打工，我和弟弟在老家和爷爷奶奶住，从小爷爷奶奶就教育我要为你家里人考虑，{/dede:field}
{dede:field name='title'}爸爸要了八万彩礼，让我嫁给了一个老实男人，每晚让我苦不堪言{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='litpic'}{/dede:field}
