<?php
$z[0]=Array("field","Phoenix New Media, Investor Rel",0,72);
$z[0][4]['name']="keywords";
$z[1]=Array("field","Phoenix New Media - Investor Relations",74,156);
$z[1][4]['name']="description";
$z[2]=Array("field","凤凰新媒体 Phoenix New Media - Investor Relations -",158,252);
$z[2][4]['name']="title";
$z[3]=Array("field","",254,293);
$z[3][4]['name']="writer";
$z[4]=Array("field","",295,334);
$z[4][4]['name']="source";
$z[5]=Array("field","",336,376);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",378,415);
$z[6][4]['name']="body";
$z[7]=Array("field","",417,456);
$z[7][4]['name']="litpic";

?>