{dede:noteinfo notename="科技" channelid="1" macthtype="string"
refurl="http://www.cnbeta.com/topics/138.htm" sourcelang="utf-8" cosort="asc" isref="no" exptime="10" usemore="0" /}

{dede:listrule sourcetype="batch" rssurl="https://sh.qihoo.com/2s21tsby2jh?uid=8e3e72bb25f6648484863a5d75893032&sign=look" regxurl="http://www.cnbeta.com/articles/tech/(*).htm"
startid="1" endid="5" addv="1" urlrule="area"
 musthas=".htm" nothas="" listpic="1" usemore="0"}
    {dede:addurls}{/dede:addurls}
    {dede:batchrule}{/dede:batchrule}
    {dede:regxrule}{/dede:regxrule}
    {dede:areastart}<div class="items-area">{/dede:areastart}
    {dede:areaend}<div class="loading-bar J_an_load">{/dede:areaend}
{/dede:listrule}
