<?php
$z[0]=Array("noteinfo","",0,183);
$z[0][4]['notename']="科技";
$z[0][4]['channelid']="1";
$z[0][4]['macthtype']="string";
$z[0][4]['refurl']="http://www.cnbeta.com/topics/138.htm";
$z[0][4]['sourcelang']="utf-8";
$z[0][4]['cosort']="asc";
$z[0][4]['isref']="no";
$z[0][4]['exptime']="10";
$z[0][4]['usemore']="0";
$z[1]=Array("listrule","\r\n    {dede:addurls}{/dede:addurls}\r\n    {dede:batchrule}{/dede:batchrule}\r\n    {dede:regxrule}{/dede:regxrule}\r\n    {dede:areastart}<div class=\"items-area\">{/dede:areastart}\r\n    {dede:areaend}<div class=\"loading-bar J_an_load\">{/dede:areaend}\r\n",187,724);
$z[1][4]['sourcetype']="batch";
$z[1][4]['rssurl']="https://sh.qihoo.com/2s21tsby2jh?uid=8e3e72bb25f6648484863a5d75893032&sign=look";
$z[1][4]['regxurl']="http://www.cnbeta.com/articles/tech/(*).htm";
$z[1][4]['startid']="1";
$z[1][4]['endid']="5";
$z[1][4]['addv']="1";
$z[1][4]['urlrule']="area";
$z[1][4]['musthas']=".htm";
$z[1][4]['nothas']="";
$z[1][4]['listpic']="1";
$z[1][4]['usemore']="0";

?>