<li class="">
                <div class="media media-lg">
                  <div class="media-left"> <a href="[field:arcurl/]" title="[field:title/]" target='_self'> <img class="media-object" src="http://demo.moke8.com/m241953/uploads/allimg/171228/1-1G22Q121020-L.jpg" style='height:150px;' alt="住建部明确：明年楼市有变化调控政策将改变"> </a> </div>
                  <div class="media-body">
                    <h4 class="media-heading"> <a href="[field:arcurl/]" title="[field:title/]" target='_self'>[field:title/]</a> </h4>
                    <p class="des">[field:description function='cn_substr(@me,250)'/]......</p>
                    <p class="info"> <span>日期：[field:pubdate function='strftime("%Y-%m-%d",@me)'/] [field:typename/]</span> 
					
					<i class="icon wb-eye margin-right-5" aria-hidden="true"></i>	 
					<span>				
					[field:click/]
					</span> 
										
										</p>
                  </div>
                </div>
              </li>