<?php
$z[0]=Array("arcurl","",113,128);
$z[1]=Array("title","",137,151);
$z[2]=Array("arcurl","",476,491);
$z[3]=Array("title","",500,514);
$z[4]=Array("title","",531,545);
$z[5]=Array("description","",592,642);
$z[5][4]['function']="cn_substr(@me,250)";
$z[6]=Array("pubdate","",706,758);
$z[6][4]['function']="strftime(\"%Y-%m-%d\",@me)";
$z[7]=Array("typename","",759,776);
$z[8]=Array("click","",885,899);

?>