{dede:field name='keywords'}房屋建筑工程施工总承包{/dede:field}
{dede:field name='description'}资质管家(zizhiguanjia.com)是国内首家建筑行业垂直领域的服务平台，创立于2013年，隶属于伯乐通(北京)教育咨询有限公司。致力于为建筑行业创业者及中小建筑企业提供高效的、低价、专{/dede:field}
{dede:field name='title'}房屋建筑工程施工总承包资质申报-资质管家{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='litpic'}{/dede:field}
