{dede:noteinfo notename="资质" channelid="1" macthtype="string"
    refurl="http://www.zizhiguanjia.com/zs/9653.html" sourcelang="utf-8" cosort="asc"
  isref="no" exptime="10" usemore="0" /}
{dede:listrule sourcetype="batch" rssurl="http://" regxurl="http://www.zizhiguanjia.com/zs/(*).html"
startid="1" endid="5" addv="1" urlrule="area" musthas=".html"
 nothas="" listpic="1" usemore="0"}
    {dede:addurls}{/dede:addurls}
    {dede:batchrule}{/dede:batchrule}
    {dede:regxrule}{/dede:regxrule}
    {dede:areastart}<div class="zsbase-r">{/dede:areastart}
    {dede:areaend}{/dede:areaend}
{/dede:listrule}
