<?php
$z[0]=Array("field","安防资质",0,53);
$z[0][4]['name']="keywords";
$z[1]=Array("field","安防资质办理对于企业人员有什么要求? 建筑企业如果想申请安防资质，企业相关人员必须通过技术人员培训和造价员培训，并获得相应证书。那么，安防资质办理对于企业人员有什么",55,341);
$z[1][4]['name']="description";
$z[2]=Array("field","安防资质办理对于企业人员有什么要求?-资质管家",343,446);
$z[2][4]['name']="title";
$z[3]=Array("field","",448,487);
$z[3][4]['name']="writer";
$z[4]=Array("field","",489,528);
$z[4][4]['name']="source";
$z[5]=Array("field","",530,570);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",572,609);
$z[6][4]['name']="body";
$z[7]=Array("field","",611,650);
$z[7][4]['name']="litpic";

?>