<?php
$z[0]=Array("field","",0,41);
$z[0][4]['name']="keywords";
$z[1]=Array("field","",43,87);
$z[1][4]['name']="description";
$z[2]=Array("field","松花江今年最后一网 大鱼出水即冻成“冰棍” _资讯频道_凤凰网",89,212);
$z[2][4]['name']="title";
$z[3]=Array("field","",214,253);
$z[3][4]['name']="writer";
$z[4]=Array("field","",255,294);
$z[4][4]['name']="source";
$z[5]=Array("field","",296,336);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",338,375);
$z[6][4]['name']="body";
$z[7]=Array("field","",377,416);
$z[7][4]['name']="litpic";

?>