{dede:field name='keywords'}原生营销,原生营销研究院{/dede:field}
{dede:field name='description'}凤凰影响立足于互联网、移动互联网世界，及时传递最新营销资讯，推送经典营销案例，发布重磅营销资源，打造原生营销，乃至网络营销第一站。{/dede:field}
{dede:field name='title'}原生营销{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='litpic'}{/dede:field}
