{dede:noteinfo notename="资质" channelid="1" macthtype="string"
    refurl="http://www.zizhiguanjia.com/zs/9653.html" sourcelang="utf-8" cosort="asc"
  isref="no" exptime="10" usemore="0" /}
{dede:listrule sourcetype="hand" rssurl="http://" regxurl="http://www.zizhiguanjia.com/zs/(*).html"
startid="1" endid="3554" addv="1" urlrule="area" musthas=""
 nothas="" listpic="1" usemore="0"}
    {dede:addurls}http://www.zizhiguanjia.com/zs/9653.html
http://www.zizhiguanjia.com/zs/9654.html
http://www.zizhiguanjia.com/zs/9655.html{/dede:addurls}
    {dede:batchrule}{/dede:batchrule}
    {dede:regxrule}{/dede:regxrule}
    {dede:areastart}{/dede:areastart}
    {dede:areaend}{/dede:areaend}
{/dede:listrule}
