{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}现如今，正是2018年新农合的缴费期，有不少农民反映新农合的缴费标准有所提高，由之前的每人每年150元上涨到了180元，部分地区甚至已经上涨到了每人每年200多元。而针对这一现象，{/dede:field}
{dede:field name='title'}明年开始，农民可以免费治病了，看这些病将不用再花一分钱！{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='litpic'}{/dede:field}
