<div class="met-index-about met-index-body">
  <div class="container ">
    <div class="about_img col-sm-12 col-md-4 col-lg-4" data-animate="zoomIn"  data-plugin="appear" data-repeat="false"> <img data-original="[field:picname/]" /></div>
    <div class="about_cont col-sm-12 col-md-8 col-lg-8">
      <h3 class="invisible" data-plugin="appear" data-animate="fade" data-repeat="false">最新发布 > [field:title/]</h3>
      <p class="desc invisible animation-delay-100" data-plugin="appear" data-animate="fadeInDown" data-repeat="false" >[field:typelink/]</p>
      <p class="desc invisible animation-delay-200" data-plugin="appear" data-animate="fadeInDown" data-repeat="false"></p>
      <div class="met-editor no-gallery lazyload clearfix invisible animation-delay-300" data-plugin="appear" data-animate="fadeInDown" data-repeat="false">  [field:description function="cn_substr(@me,500)"/]...</div>
      <a href="[field:arcurl/]" class="more" data-animate="bounceIn"></a> </div>
  </div>
</div>