<?php
$z[0]=Array("include","",0,35);
$z[0][4]['filename']="head.htm";
$z[1]=Array("field","",187,209);
$z[1][4]['name']="position";
$z[2]=Array("productimagelist","\r\n            <div class='slick-slide lg-item-box' data-src=\"[field:imgsrc/]\"  data-exthumbimage=\"[field:imgsrc/]\" style=\"height: 441px;\">\r\n\r\n			<span> <img src=\"[field:imgsrc/]\" data-src='[field:imgsrc/]' class=\"img-responsive\" alt=\"[field:text/]\" /> </span> </div>\r\n			\r\n			",635,958);
$z[3]=Array("global","",1020,1052);
$z[3][4]['name']="cfg_templets_skin";
$z[4]=Array("global","",1097,1129);
$z[4][4]['name']="cfg_templets_skin";
$z[5]=Array("global","",1173,1205);
$z[5][4]['name']="cfg_templets_skin";
$z[6]=Array("global","",1241,1273);
$z[6][4]['name']="cfg_templets_skin";
$z[7]=Array("field","",1531,1550);
$z[7][4]['name']="title";
$z[8]=Array("field","",1590,1615);
$z[8][4]['name']="description";
$z[9]=Array("global","",2515,2547);
$z[9][4]['name']="cfg_templets_skin";
$z[10]=Array("field","",2974,2992);
$z[10][4]['name']="body";
$z[11]=Array("likeart","\r\n<li> <a href=\"[field:arcurl/]\" target=\"_blank\" class=\"img\" title=\"[field:title/]\"> <img data-original=\"[field:picname/]\" class=\"cover-image\" style='height:200px;' alt=\"[field:title/]\"> </a> <a href=\"[field:arcurl/]\" target=\"_blank\" class=\"txt\" title=\"[field:title/]\">[field:title/]</a> </li>\r\n",3609,3955);
$z[11][4]['row']="5";
$z[11][4]['titlelen']="50";
$z[12]=Array("global","",4063,4095);
$z[12][4]['name']="cfg_templets_skin";
$z[13]=Array("global","",4388,4420);
$z[13][4]['name']="cfg_templets_skin";
$z[14]=Array("global","",4713,4745);
$z[14][4]['name']="cfg_templets_skin";
$z[15]=Array("include","",5140,5177);
$z[15][4]['filename']="footer.htm";

?>