<?php
$z[0]=Array("include","",0,35);
$z[0][4]['filename']="head.htm";
$z[1]=Array("field","",268,287);
$z[1][4]['name']="title";
$z[2]=Array("field","",331,387);
$z[2][4]['name']="pubdate";
$z[2][4]['function']="MyDate('Y-m-d H:i',@me)";
$z[3]=Array("adminname","",402,419);
$z[4]=Array("field","",514,541);
$z[4][4]['name']="phpurl";
$z[5]=Array("field","",565,588);
$z[5][4]['name']="id";
$z[6]=Array("field","",593,617);
$z[6][4]['name']="mid";
$z[7]=Array("field","",1084,1102);
$z[7][4]['name']="body";
$z[8]=Array("prenext","",1444,1469);
$z[8][4]['get']="pre";
$z[9]=Array("prenext","",1565,1591);
$z[9][4]['get']="next";
$z[10]=Array("likeart","\r\n                <li class=\"list-group-item\"><a href=\"[field:arcurl/]\" title=\"[field:fulltitle/]\" target='_self'>[field:title/]</a></li>\r\n",2433,2623);
$z[10][4]['row']="5";
$z[10][4]['titlelen']="40";
$z[11]=Array("field","",2730,2750);
$z[11][4]['name']="source";
$z[12]=Array("include","",2917,2954);
$z[12][4]['filename']="footer.htm";

?>