<?php
$z[0]=Array("field","",0,41);
$z[0][4]['name']="keywords";
$z[1]=Array("field","原标题：美国调整高血压标准 中国网友拿起了体检报告…… 中新网北京11月16日电(汤琪)近日，美",43,215);
$z[1][4]['name']="description";
$z[2]=Array("field","美国调整高血压标准 中国网友拿起了体检报告……_凤凰资讯",217,335);
$z[2][4]['name']="title";
$z[3]=Array("field","",337,376);
$z[3][4]['name']="writer";
$z[4]=Array("field","",378,417);
$z[4][4]['name']="source";
$z[5]=Array("field","",419,459);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",461,498);
$z[6][4]['name']="body";
$z[7]=Array("field","",500,539);
$z[7][4]['name']="litpic";

?>