{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}原标题：美国调整高血压标准 中国网友拿起了体检报告…… 中新网北京11月16日电(汤琪)近日，美{/dede:field}
{dede:field name='title'}美国调整高血压标准 中国网友拿起了体检报告……_凤凰资讯{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='litpic'}{/dede:field}
