<?php
$z[0]=Array("field","建筑施工总承包资质升级",0,74);
$z[0][4]['name']="keywords";
$z[1]=Array("field","资质升级是很多企业资质申办成功后必走的流程，而业绩是资质升级的关键，今天资质管家小编就和各位老板介绍一下建筑施工总承包资质升级业绩如何备案！ 一、业绩备案时间： 企",76,362);
$z[1][4]['name']="description";
$z[2]=Array("field","建筑施工总承包资质升级业绩如何备案-资质管家",364,466);
$z[2][4]['name']="title";
$z[3]=Array("field","",468,507);
$z[3][4]['name']="writer";
$z[4]=Array("field","",509,548);
$z[4][4]['name']="source";
$z[5]=Array("field","",550,590);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",592,629);
$z[6][4]['name']="body";
$z[7]=Array("field","",631,670);
$z[7][4]['name']="litpic";

?>