<?php
$z[0]=Array("field","",0,41);
$z[0][4]['name']="keywords";
$z[1]=Array("field","原标题：白人男子无端辱骂掌掴亚裔乘客：你个中国黑鬼！海外网11月16日电 当地时间13日晚10点，美国加州旧金山市湾区列车上发生种族歧视事件。一名白人男子在车厢内，以带有种",43,327);
$z[1][4]['name']="description";
$z[2]=Array("field","白人男子无端辱骂掌掴亚裔乘客：你个“中国黑鬼”_凤凰资讯",329,449);
$z[2][4]['name']="title";
$z[3]=Array("field","",451,490);
$z[3][4]['name']="writer";
$z[4]=Array("field","",492,531);
$z[4][4]['name']="source";
$z[5]=Array("field","",533,573);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",575,612);
$z[6][4]['name']="body";
$z[7]=Array("field","",614,653);
$z[7][4]['name']="litpic";

?>