{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}原标题：白人男子无端辱骂掌掴亚裔乘客：你个中国黑鬼！海外网11月16日电 当地时间13日晚10点，美国加州旧金山市湾区列车上发生种族歧视事件。一名白人男子在车厢内，以带有种{/dede:field}
{dede:field name='title'}白人男子无端辱骂掌掴亚裔乘客：你个“中国黑鬼”_凤凰资讯{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='litpic'}{/dede:field}
