{dede:field name='keywords'}转让建筑资质注意事项包{/dede:field}
{dede:field name='description'}建筑企业为了承接工程，又不想浪费时间办理资质，大都会选择建筑资质转让，直接收购有其他建筑企业的资质。进行转让的过程中，需要注意的事情有很多，今天资质管家小编主要从{/dede:field}
{dede:field name='title'}转让建筑资质注意事项包括哪些-资质管家{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='litpic'}{/dede:field}
