{dede:field name='keywords'}凤凰,凤凰网,凤凰新媒体{/dede:field}
{dede:field name='description'}凤凰网是中国领先的综合门户网站，提供含文图音视频的全方位综合新闻资讯、深度访谈、观点评论、财经产品、互动应用、分享社区等服务，同时与凤凰无线、凤凰宽频形成三屏联动{/dede:field}
{dede:field name='title'}凤凰网{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}{/dede:field}
{dede:field name='litpic'}/uploads/allimg/c180130/151HM135940-2L06.jpg{/dede:field}
