<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="3";
$z[0][4]['col']="4";
$z[0][4]['value']="2";
$z[1]=Array("img"," /uploads/allimg/180209/1-1P209131136.png ",93,250);
$z[1][4]['ddimg']="/uploads/allimg/180209/1-1P209131136.png";
$z[1][4]['text']="夏至未至";
$z[1][4]['width']="680";
$z[1][4]['height']="380";
$z[2]=Array("img"," /uploads/allimg/180209/1-1P209131441.jpg ",252,410);
$z[2][4]['ddimg']="/uploads/allimg/180209/1-1P209131441.jpg";
$z[2][4]['text']="夏至未至";
$z[2][4]['width']="1200";
$z[2][4]['height']="800";

?>