<?php
$z[0]=Array("field","",175,203);
$z[0][4]['name']="typeurl";
$z[1]=Array("field","",206,235);
$z[1][4]['name']="typename";
$z[2]=Array("channel"," \r\n              <li class=\"animation-fade animation-delay-\"><a href=\"[field:typelink/]\" class=\" animation-fade \"  title=\"[field:typename/] \">[field:typename/] </a></li>\r\n              ",375,613);
$z[2][4]['type']="son";
$z[2][4]['noself']="yes";

?>