<?php
$z[0]=Array("field","机电设备安装工程资质,资",0,75);
$z[0][4]['name']="keywords";
$z[1]=Array("field","机电设备安装工程资质办理常见问题 2014年11月6日建设部颁发了最新的资质标准，其中的建筑机电安装工程专业承包资质，相关标准的要求也有所改变。那么，机电设备安装工程资质办",77,363);
$z[1][4]['name']="description";
$z[2]=Array("field","机电设备安装工程资质办理常见问题-资质管家",365,464);
$z[2][4]['name']="title";
$z[3]=Array("field","",466,505);
$z[3][4]['name']="writer";
$z[4]=Array("field","",507,546);
$z[4][4]['name']="source";
$z[5]=Array("field","",548,588);
$z[5][4]['name']="pubdate";
$z[6]=Array("field","",590,627);
$z[6][4]['name']="body";
$z[7]=Array("field","",629,668);
$z[7][4]['name']="litpic";

?>