{dede:noteinfo notename="科技" channelid="1" macthtype="string"
refurl="http://www.nbd.com.cn/articles/2018-01-30/1188389.html" sourcelang="utf-8" cosort="asc" isref="no" exptime="10" usemore="0" /}

{dede:listrule sourcetype="hand" rssurl="https://sh.qihoo.com/2s21tsby2jh?uid=8e3e72bb25f6648484863a5d75893032&sign=look" regxurl="http://"
startid="1" endid="" addv="1" urlrule="area"
 musthas=".html" nothas="" listpic="1" usemore="0"}
    {dede:addurls}http://www.nbd.com.cn/articles/2018-01-30/1188389.html
http://www.cnbeta.com/articles/tech/694097.htm{/dede:addurls}
    {dede:batchrule}{/dede:batchrule}
    {dede:regxrule}{/dede:regxrule}
    {dede:areastart}<div class="mod-instantNews">{/dede:areastart}
    {dede:areaend}<div class="col-right">{/dede:areaend}
{/dede:listrule}
