<?php
$z[0]=Array("global","",139,165);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("global","",225,251);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("type","<li id=\"navbar-category-1\"><a href=\"[field:typelink /]\"><i class=\"icon-tasks\"></i> [field:typename /]</a></li>",480,624);
$z[2][4]['typeid']="1";
$z[3]=Array("type","<li id=\"navbar-category-1\"><a href=\"[field:typelink /]\"><i class=\"icon-desktop\"></i> [field:typename /]</a></li>",638,784);
$z[3][4]['typeid']="2";
$z[4]=Array("type","<li id=\"navbar-category-1\"><a href=\"[field:typelink /]\"><i class=\"icon-desktop\"></i> [field:typename /]</a></li>",798,944);
$z[4][4]['typeid']="3";
$z[5]=Array("type","<li id=\"navbar-category-1\"><a href=\"[field:typelink /]\"><i class=\"icon-desktop\"></i> [field:typename /]</a></li>",948,1094);
$z[5][4]['typeid']="6";
$z[6]=Array("type","<li id=\"navbar-category-1\"><a href=\"[field:typelink /]\"><i class=\"icon-desktop\"></i> [field:typename /]</a></li>",1096,1242);
$z[6][4]['typeid']="7";
$z[7]=Array("type","<li id=\"navbar-category-1\"><a href=\"[field:typelink /]\"><i class=\"icon-desktop\"></i> [field:typename /]</a></li>",1244,1390);
$z[7][4]['typeid']="8";
$z[8]=Array("type","<li id=\"navbar-category-1\"><a href=\"[field:typelink /]\"><i class=\"icon-desktop\"></i> [field:typename /]</a></li>",1392,1538);
$z[8][4]['typeid']="9";
$z[9]=Array("type","<li id=\"navbar-page-2\"><a href=\"[field:typelink /]\"><i class=\"icon-comments\"></i> [field:typename /]</a></li>",1558,1701);
$z[9][4]['typeid']="4";

?>