<?php
$z[0]=Array("field","",165,184);
$z[0][4]['name']="title";
$z[1]=Array("global","",185,211);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("global","",255,285);
$z[2][4]['name']="cfg_description";
$z[3]=Array("global","",322,349);
$z[3][4]['name']="cfg_keywords";
$z[4]=Array("global","",679,711);
$z[4][4]['name']="cfg_templets_skin";
$z[5]=Array("global","",1547,1574);
$z[5][4]['name']="cfg_basehost";
$z[6]=Array("global","",1694,1726);
$z[6][4]['name']="cfg_templets_skin";
$z[7]=Array("global","",1991,2018);
$z[7][4]['name']="cfg_indexurl";
$z[8]=Array("channel","\r\n		  <li  class=\"dropdown margin-left-30\"><a href=\"[field:typelink/]\" title=\"[field:typename/]\">[field:typename/]</a></li>",2080,2254);
$z[8][4]['type']="top";
$z[8][4]['row']="8";
$z[9]=Array("channelartlist"," \r\n          <li class=\"dropdown margin-left-30\"> <a class=\"dropdown-toggle animation-zoomIn link \"   data-toggle=\"dropdown\" data-hover=\"dropdown\"aria-expanded=\"false\" role=\"button\" href=\"{dede:field name='typeurl'/}\" >{dede:field name='typename'/} <i class=\"fa fa-angle-down\"></i></a>\r\n           \r\n\r\n <ul class=\"dropdown-menu dropdown-menu-right bullet \" role=\"menu\" >\r\n             \r\n {dede:channel type='son' noself='yes'} \r\n              <li class=\"animation-fade animation-delay-\"><a href=\"[field:typelink/]\" class=\" animation-fade \"  title=\"[field:typename/] \">[field:typename/] </a></li>\r\n              {/dede:channel} \r\n\r\n            </ul>\r\n          </li>\r\n		  ",2840,3589);
$z[9][4]['typeid']="top";
$z[9][4]['row']="7";
$z[9][4]['type']="top";

?>