<?php
$z[0]=Array("include","",0,35);
$z[0][4]['filename']="head.htm";
$z[1]=Array("global","",144,176);
$z[1][4]['name']="cfg_templets_skin";
$z[2]=Array("global","",205,237);
$z[2][4]['name']="cfg_templets_skin";
$z[3]=Array("field","",460,489);
$z[3][4]['name']="typename";
$z[4]=Array("channel","\r\n          <li><a href='[field:typelink/]' class='link active'>[field:typename/]</a> </li>\r\n		  \r\n		  ",779,968);
$z[4][4]['row']="3";
$z[4][4]['type']="top";
$z[4][4]['reid']="1";
$z[5]=Array("list","\r\n	   <li class=\" shown\">\r\n          <div class=\"widget widget-shadow\">\r\n            <figure class=\"widget-header cover\"> <a href=\"[field:arcurl/]\" title=\"[field:shorttitle/]\" target='_self'>\r\n              <div class=\"mask\"> </div>\r\n              <img class=\"cover-image\"  src=\"[field:picname/]\" alt=\"[field:title/]\"> </a> </figure>\r\n            <h4 class=\"widget-title\"> <a href=\"[field:arcurl/]\"  title=\"[field:title/]\" target='_self'>[field:title/]</a>\r\n              <p>[field:description function=\"cn_substr(@me,30)\"/]...</p>\r\n            </h4>\r\n          </div>\r\n        </li>\r\n		",1952,2591);
$z[5][4]['pagesize']="10";
$z[5][4]['titlelen']="20";
$z[6]=Array("pagelist","",2674,2751);
$z[6][4]['listitem']="info,index,end,pre,next,pageno,option";
$z[6][4]['listsize']="1";
$z[7]=Array("include","",2901,2938);
$z[7][4]['filename']="footer.htm";

?>