<?php
$z[0]=Array("include","",0,35);
$z[0][4]['filename']="head.htm";
$z[1]=Array("field","",454,483);
$z[1][4]['name']="typename";
$z[2]=Array("list","\r\n			  <li class=\"\">\r\n                <div class=\"media media-lg\">\r\n                  <div class=\"media-left\"> <a href=\"[field:arcurl/]\" title=\"[field:title/]\" target='_self'> <img class=\"media-object\" src=\"[field:picname/]\" style='height:150px;' alt=\"[field:title/]\"> </a> </div>\r\n                  <div class=\"media-body\">\r\n                    <h4 class=\"media-heading\"> <a href=\"[field:arcurl/]\" title=\"[field:title/]\" target='_self'>[field:title/]</a> </h4>\r\n                    <p class=\"des\">[field:description function=\"cn_substr(@me,700)\"/]...</p>\r\n                    <p class=\"info\"> <span>[field:pubdate function=\"GetDateTimeMK(@me)\" /]</span> <span>[field:typename/]</span> <span><i class=\"icon wb-eye margin-right-5\" aria-hidden=\"true\"></i>[field:click/]</span> </p>\r\n                  </div>\r\n                </div>\r\n              </li>\r\n			  ",855,1749);
$z[2][4]['pagesize']="6";
$z[3]=Array("pagelist","",1834,1911);
$z[3][4]['listitem']="info,index,end,pre,next,pageno,option";
$z[3][4]['listsize']="1";
$z[4]=Array("likeart","\r\n                <li class=\"list-group-item\"><a href=\"[field:arcurl/]\" title=\"[field:title/]\" target='_self'>[field:title/]</a></li>\r\n",2781,2967);
$z[4][4]['row']="5";
$z[4][4]['titlelen']="50";
$z[5]=Array("field","",3070,3090);
$z[5][4]['name']="source";
$z[6]=Array("include","",3263,3300);
$z[6][4]['filename']="footer.htm";

?>