<?php
$z[0]=Array("include","",0,35);
$z[0][4]['filename']="head.htm";
$z[1]=Array("global","",235,267);
$z[1][4]['name']="cfg_templets_skin";
$z[2]=Array("global","",296,328);
$z[2][4]['name']="cfg_templets_skin";
$z[3]=Array("field","",551,580);
$z[3][4]['name']="typename";
$z[4]=Array("field","",754,776);
$z[4][4]['name']="position";
$z[5]=Array("loop","\r\n          <li id=\"cmt2\">\r\n            <div class=\"cmt-info\">\r\n              <div class=\"gravatar\"> <img alt=\"[field:name/]\" src=\"/style/images/0.png\" class=\"avatar avatar-45 photo\" height=\"45\" width=\"45\"> </div>\r\n              <div class=\"cmt-author\"> <a href=\"[field:arcurl/]\" rel=\"nofollow\" target=\"_blank\">[field:name/]</a> </div>\r\n            </div>\r\n            <div class=\"cmt-con\">[field:cont/]\r\n            </div>\r\n          </li>\r\n        </ol><br>\r\n        ",1198,1746);
$z[5][4]['table']="dede_diyform1";
$z[5][4]['sort']="id";
$z[5][4]['row']="30";
$z[5][4]['if']="ifcheck=1";
$z[6]=Array("include","",3607,3644);
$z[6][4]['filename']="footer.htm";

?>